import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID}from'node:crypto';import {setup,register,order,client,origin,secret}from'./fixtures.mjs';import {signQuote}from'../lib/security.mjs';import {SupabaseStore}from'../lib/store.mjs';
import {AppError}from'../lib/domain.mjs';
test('6-character registration, crypto + FX buy/sell, history and relogin',async()=>{const t=setup(),c=t.client(),r=await register(c,'Alice','aB3!xy');assert.equal(r.account.state.cashMinor,10000000);assert.equal(r.account.hash,undefined);assert.equal(r.account.lookup,undefined);assert.equal((await c.call('trade',await order(c))).status,200);assert.equal((await c.call('trade',await order(c,{symbol:'USDJPY',quantity:10000000}))).status,200);assert.equal((await c.call('portfolio')).account.state.positions.length,2);assert.equal((await c.call('trade',await order(c,{side:'sell'}))).status,200);assert.equal((await c.call('history')).items.length,3);const token=c.cookie;await c.call('logout',{});assert.equal((await c.call('portfolio',undefined,{}, {cookie:token})).status,401);assert.equal((await c.call('login',{password:r.password})).account.id,r.account.id);assert.equal((await c.call('portfolio')).account.state.positions[0].symbol,'USDJPY');});
test('chart periods and reference history are separate from signed execution quotes',async()=>{const t=setup(),c=t.client();await register(c);const config=await c.call('config');assert.deepEqual(config.chartPeriods.crypto,['24H','7D','30D','90D','1Y']);assert.deepEqual(config.chartPeriods.fx,['7D','1M','3M','1Y','5Y']);const chart=await c.call('price-history',undefined,{symbol:'BTC',period:'24H'});assert.equal(chart.status,200);assert.equal(chart.chart.points.length,24);assert.equal(chart.quoteToken,undefined);assert.equal(chart.chart.referenceOnly,true);const quote=await c.call('quote',undefined,{symbol:'BTC'});assert.equal(typeof quote.quoteToken,'string');});
test('chart failure does not disable current quote or trading',async()=>{const t=setup(),c=t.client();await register(c);t.market.history=async()=>{throw new AppError('CHART_UNAVAILABLE','chart unavailable',503);};assert.equal((await c.call('price-history',undefined,{symbol:'BTC',period:'24H'})).status,503);assert.equal((await c.call('quote',undefined,{symbol:'BTC'})).status,200);assert.equal((await c.call('trade',await order(c))).status,200);});
test('short passwords and missing username rejected',async()=>{const c=setup().client();assert.equal((await c.call('register',{username:'test',password:'12345'})).status,400);assert.equal((await c.call('register',{password:'123456'})).status,400);});
test('duplicate username and password never grant access',async()=>{const t=setup(),a=t.client(),b=t.client();const r=await register(a,'Alice');assert.equal((await b.call('register',{username:'ALICE',password:'another-fixture'})).error.code,'USERNAME_UNAVAILABLE');assert.equal((await b.call('register',{username:'other',password:r.password})).error.code,'PASSWORD_UNAVAILABLE');assert.equal((await b.call('session')).account,null);});
test('username editing and ranking reflect all accounts and ties',async()=>{const t=setup(),a=t.client(),b=t.client();await register(a,'Alice');await register(b,'Bob');await a.call('username',{username:'NewAlice'});const rows=(await a.call('leaderboard')).items;assert.equal(rows.length,2);assert.equal(rows.find(r=>r.me).username,'NewAlice');assert.deepEqual(rows.map(r=>r.rank),[1,1]);assert.deepEqual(Object.keys(rows[0]).sort(),['me','rank','totalMinor','username']);assert.equal((await a.call('username',{username:'bob'})).status,409);});
test('untrusted username markup rejected',async()=>{const c=setup().client();await register(c);for(const name of ['<script>','a\u0000b','a\u202eb','x','x'.repeat(21),{},null])assert.equal((await c.call('username',{username:name})).status,400);});
test('ranking revalues holdings and never replaces unavailable prices with zero or basis',async()=>{const t=setup(),a=t.client(),b=t.client();await register(a,'Alice');await register(b,'Bob');await a.call('trade',await order(a));t.market.quote=async()=>{throw Error('unavailable');};const r=await b.call('leaderboard');assert.equal(r.items[0].username,'Bob');assert.equal(r.items[1].totalMinor,null);assert.equal(r.items[1].rank,null);assert.equal((await a.call('portfolio')).totalMinor,null);});
test('deletion cascades sessions/journal and disappears from ranking',async()=>{const t=setup(),a=t.client(),b=t.client(),other=t.client();const {account,password}=await register(a,'Alice');await register(other,'Other');await b.call('login',{password});await a.call('trade',await order(a));assert.equal((await a.call('delete-account',{password})).error.code,'CONFIRM_DELETE');assert.equal((await a.call('delete-account',{password:'wrong-value',confirm:'DELETE'})).status,401);assert.equal((await a.call('delete-account',{password,confirm:'DELETE'})).status,200);assert.equal(await t.store.getAccount(account.id),null);assert.equal((await b.call('portfolio')).status,401);assert.deepEqual((await other.call('leaderboard')).items.map(r=>r.username),['Other']);});
test('old journal retained separately from new initial wallet',async()=>{const t=setup(),c=t.client(),r=await register(c);t.store.data.accounts[r.account.id].legacyTrades=[{requestId:randomUUID(),symbol:'9434.T',name:'Archived',quantity:100,quantityScale:1,legacy:true,side:'buy',priceMinor:24590,totalMinor:2459000,executedAt:1,source:'yahoo'}];assert.equal((await c.call('history')).items[0].legacy,true);assert.equal((await c.call('portfolio')).totalMinor,10000000);assert.equal((await c.call('quote',undefined,{symbol:'9434.T'})).status,400);});
test('parallel duplicates and lost reply retry create one ledger entry',async()=>{const t=setup(),c=t.client();await register(c);const o=await order(c);const rs=await Promise.all([c.call('trade',o),c.call('trade',o)]);assert.equal(rs.filter(r=>r.status===200).length,2);assert.equal((await c.call('history')).items.length,1);t.advance(120000);assert.equal((await c.call('trade',o)).duplicate,true);assert.equal((await c.call('trade',{...o,requestId:randomUUID()})).error.code,'QUOTE_EXPIRED');});
test('changed duplicate and cross-account quote rejected',async()=>{const t=setup(),a=t.client(),b=t.client();await register(a,'Alice');await register(b,'Bob');const o=await order(a);assert.equal((await b.call('trade',o)).error.code,'QUOTE_TOKEN');await a.call('trade',o);assert.equal((await a.call('trade',{...o,quantity:2000})).error.code,'IDEMPOTENCY_CONFLICT');});
test('parallel buys cannot overspend',async()=>{const t=setup(),c=t.client();await register(c);const o=await order(c,{quantity:6000});const rs=await Promise.all([c.call('trade',o),c.call('trade',{...o,requestId:randomUUID()})]);assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal((await c.call('portfolio')).account.state.cashMinor,4000000);});
test('parallel sales cannot oversell',async()=>{const t=setup(),c=t.client();await register(c);await c.call('trade',await order(c));const o=await order(c,{side:'sell'});const rs=await Promise.all([c.call('trade',o),c.call('trade',{...o,requestId:randomUUID()})]);assert.equal(rs.filter(r=>r.status===200).length,1);});
test('client supplied price ignored and quote signing key separated',async()=>{const t=setup(),c=t.client(),r=await register(c);const o=await order(c);const q=await t.market.quote('BTC');const forged=signQuote({...q,priceMinor:1},secret,r.account.id,t.clock());assert.equal((await c.call('trade',{...o,quoteToken:forged})).status,400);const buy=await c.call('trade',{...o,priceMinor:1});assert.equal(buy.trade.priceMinor,1000000000);});
test('anonymous endpoints protected and CSRF stays enforced',async()=>{const t=setup(),c=t.client();for(const action of ['search','quote','price-history','history','portfolio','leaderboard'])assert.equal((await c.call(action)).status,401);const reg=await c.call('register',{username:'attacker',password:'localfixture'},{},{origin:'https://not-the-app.example'});assert.equal(reg.status,403);assert.equal(Object.keys(t.store.data.accounts).length,0);});
test('crypto key absence does not disable FX or account creation',async()=>{const t=setup({key:''}),c=t.client();await register(c);assert.equal((await c.call('config')).markets.crypto,'key-required');assert.equal((await c.call('quote',undefined,{symbol:'BTC'})).error.code,'CRYPTO_SETUP');assert.equal((await c.call('quote',undefined,{symbol:'USDJPY'})).status,200);});
test('cloud adapter rejects arbitrary URLs and does not send secret keys as JWTs',async()=>{assert.throws(()=>new SupabaseStore('http://localhost','x'));let headers,url;const store=new SupabaseStore('https://example.supabase.co','sb_secret_fixture',async(u,o)=>{headers=o.headers;url=u;return Response.json([]);});assert.equal(await store.getAccount('x&y'),null);assert.ok(url.includes('x%26y'));assert.equal(headers.apikey,'sb_secret_fixture');assert.equal(headers.Authorization,undefined);});
test('cloud maps independent wallet, never the old balance',()=>{const s=new SupabaseStore('https://example.supabase.co','fixture');assert.equal(s.account({id:'a',username:'Owner',market:'yahoo',state:{cashMinor:42},created_at:'2026-01-01',practice_wallets:{state:{cashMinor:10000000}}}).state.cashMinor,10000000);assert.throws(()=>s.account({id:'a',state:{cashMinor:42}}),e=>e.code==='MIGRATION_REQUIRED');});

test('general and per-market comments are authenticated, escaped by UI contract, limited and isolated by room',async()=>{const t=setup(),a=t.client(),b=t.client();await register(a,'Alice');await register(b,'Bob');let r=await a.call('comment',{room:'GENERAL',body:'ドル円どうなる？'});assert.equal(r.status,201);await b.call('comment',{room:'BTC',body:'BTCを見ています'});assert.deepEqual((await a.call('comments',undefined,{room:'GENERAL'})).items.map(x=>x.body),['ドル円どうなる?']);assert.deepEqual((await a.call('comments',undefined,{room:'BTC'})).items.map(x=>x.username),['Bob']);assert.equal((await a.call('comment',{room:'BAD',body:'x'})).status,400);assert.equal((await a.call('comment',{room:'BTC',body:'<script>alert(1)</script>'})).status,201);assert.equal((await a.call('comment',{room:'BTC',body:'x'.repeat(281)})).status,400);});
test('comments require login and are removed with the virtual account',async()=>{const t=setup(),a=t.client(),guest=t.client();const {password}=await register(a,'Alice');assert.equal((await guest.call('comments',undefined,{room:'GENERAL'})).status,401);await a.call('comment',{room:'GENERAL',body:'hello'});await a.call('delete-account',{password,confirm:'DELETE'});assert.equal(t.store.data.comments.length,0);});

test('username maximum is 15 characters for registration and rename',async()=>{const t=setup(),a=t.client();assert.equal((await a.call('register',{username:'1234567890123456',password:'long-enough-password'})).status,400);await register(a,'123456789012345');assert.equal((await a.call('username',{username:'1234567890123456'})).status,400);});
test('leaderboard reports sell count including zero',async()=>{const t=setup(),a=t.client(),b=t.client();await register(a,'Alice');await register(b,'Bob');let r=await a.call('leaderboard');assert.equal(r.items.find(x=>x.username==='Alice').sellCount,0);assert.equal(r.items.find(x=>x.username==='Bob').sellCount,0);});
