import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { initialState, INITIAL_CASH, normalizeSymbol, executeTrade } from '../lib/domain.mjs';
const quote={symbol:'7203.T',name:'テスト',priceMinor:10005,currency:'JPY',source:'demo',quoteAt:null};
const order=(side='buy',quantity=3,extra={})=>({symbol:'7203.T',side,quantity,requestId:randomUUID(),...extra});
test('starts at exactly 100,000 JPY',()=>assert.equal(initialState().cashMinor,10_000_000));
test('normalizes Japanese full-width and alpha stock codes',()=>{assert.equal(normalizeSymbol('７２０３'),'7203.T');assert.equal(normalizeSymbol('130a'),'130A.T');});
for(const symbol of ['AAPL','../api','7203.T/../../','0A00','72030','7203.US','^N225'])test(`rejects invalid symbol ${symbol}`,()=>assert.throws(()=>normalizeSymbol(symbol)));
test('buy persists exact minor units without mutating original',()=>{const s=initialState();const r=executeTrade(s,order(),quote,100);assert.equal(r.state.cashMinor,INITIAL_CASH-30015);assert.equal(r.state.positions[0].shares,3);assert.equal(s.positions.length,0);assert.equal(r.trade.totalMinor,30015);});
for(const quantity of [0,-1,1.5,NaN,Infinity,1_000_001,'1',null])test(`rejects quantity ${String(quantity)}`,()=>assert.throws(()=>executeTrade(initialState(),order('buy',quantity),quote,100)));
test('rejects insufficient cash',()=>assert.throws(()=>executeTrade(initialState(),order('buy',1000),quote,1),e=>e.code==='INSUFFICIENT_CASH'));
test('rejects naked short selling',()=>assert.throws(()=>executeTrade(initialState(),order('sell',1),quote,1),e=>e.code==='INSUFFICIENT_SHARES'));
test('rejects overselling',()=>{const a=executeTrade(initialState(),order('buy',2),quote,1);assert.throws(()=>executeTrade(a.state,order('sell',3),quote,2));});
test('weighted basis and residual allocation preserve all cost',()=>{
 let s=executeTrade(initialState(),order('buy',2),quote,1).state;
 s=executeTrade(s,order('buy',1),{...quote,priceMinor:10006},2).state;
 assert.equal(s.positions[0].costMinor,30016);
 s=executeTrade(s,order('sell',1),{...quote,priceMinor:10100},3).state;
 assert.equal(s.positions[0].costMinor,20011);
 s=executeTrade(s,order('sell',2),{...quote,priceMinor:10100},4).state;
 assert.equal(s.positions.length,0);assert.equal(s.realizedMinor,284);assert.equal(s.cashMinor,INITIAL_CASH+284);
});
for(const price of [0,-1,NaN,Infinity,1.1,Number.MAX_SAFE_INTEGER])test(`rejects invalid price ${price}`,()=>assert.throws(()=>executeTrade(initialState(),order(),{...quote,priceMinor:price},1)));
test('rejects mismatched currency and symbol',()=>{assert.throws(()=>executeTrade(initialState(),order(),{...quote,currency:'USD'},1));assert.throws(()=>executeTrade(initialState(),order(),{...quote,symbol:'6758.T'},1));});
test('sale can realize a loss',()=>{const a=executeTrade(initialState(),order(),quote,1);const r=executeTrade(a.state,order('sell'),{...quote,priceMinor:9000},2);assert.equal(r.state.realizedMinor,-3015);});
