import { createMarket } from '../lib/market.mjs';
import { MemoryStore } from '../lib/store.mjs';
import { createApp } from '../lib/app.mjs';
import { randomUUID } from 'node:crypto';
export const origin='http://localhost:3000',secret='fixture-secret-not-for-production-'.repeat(3);
export function payload(url,time){
 const u=new URL(url,'https://fixture.invalid');
 if(u.pathname.includes('/market_chart')){const days=Number(u.searchParams.get('days')),count=days===1?24:Math.min(days*4,360),start=time-days*86400000;return{prices:Array.from({length:count},(_,i)=>[Math.round(start+i*(time-start)/(count-1)),10000000+i*1000]),market_caps:[],total_volumes:[]};}
 if(u.pathname.includes('..')){const [startText,endText]=u.pathname.split('/').at(-1).split('..'),start=Date.parse(startText+'T00:00:00Z'),end=Date.parse(endText+'T00:00:00Z'),rates={};for(let at=start;at<=end;at+=86400000){const d=new Date(at);if(![0,6].includes(d.getUTCDay()))rates[d.toISOString().slice(0,10)]={JPY:160+(at-start)/864000000,USD:1.1,GBP:.85,AUD:1.6};}return{amount:1,base:'EUR',start_date:startText,end_date:endText,rates};}
 return url.includes('coingecko')?Object.fromEntries([['bitcoin',10000000],['ethereum',400000],['solana',20000],['ripple',250]].map(([id,jpy])=>[id,{jpy,last_updated_at:Math.floor(time/1000)}])):{base:'EUR',amount:1,date:new Date(time).toISOString().slice(0,10),rates:{JPY:160,USD:1.1,GBP:0.85,AUD:1.6}};
}
export function setup({store=new MemoryStore(),fetcher=null,key='fixture-api-key',time=Date.now(),historyDelay=false}={}){let now=time;const market=createMarket({store,clock:()=>now,coinGeckoKey:key,fetcher:fetcher|| (async url=>{if(historyDelay&&url.includes('market_chart')){const days=new URL(url).searchParams.get('days');await new Promise(r=>setTimeout(r,days==='7'?150:days==='30'?10:5));}if(historyDelay&&url.includes('..'))await new Promise(r=>setTimeout(r,250));return Response.json(payload(url,now));})});const app=createApp({store,market,secret,quoteSecret:'separate-private-fixture-signing-key',origin,secure:false,clock:()=>now});return{store,market,app,clock:()=>now,advance:n=>now+=n,client:()=>client(app)};}
export function client(app){let cookie='';return{get cookie(){return cookie;},async call(action,body,params={},headers={}){const r=await app(new Request(`${origin}/api/index?${new URLSearchParams({action,...params})}`,{method:body===undefined?'GET':'POST',headers:{cookie,origin,'content-type':'application/json','x-practice-request':'1',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,headers:r.headers,...await r.json()};}};}
export async function register(c,name='test_'+randomUUID().slice(0,8),password='local-fixture-'+randomUUID()){const r=await c.call('register',{username:name,password});if(r.status!==200)throw Error(JSON.stringify(r));return{account:r.account,password};}
export async function order(c,extra={}){const symbol=extra.symbol||'BTC';const r=await c.call('quote',undefined,{symbol});if(r.status!==200)throw Error(JSON.stringify(r));return{symbol,side:'buy',quantity:1000,requestId:randomUUID(),quoteToken:r.quoteToken,...extra};}
