import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {browserLanguage,requestLanguage,withLocalization} from '../lib/locale.mjs';
import {initialChoice,languagePath,preferredBrowserLanguage} from '../public/site-language.js';
import {translateSource,buildSite} from '../scripts/localize.mjs';
import {setup,client,register,order,origin} from './fixtures.mjs';
const req=(headers={},query='')=>new Request(origin+'/api/index?action=locale'+query,{headers});
test('Japan defaults to Japanese even with an English browser',()=>assert.deepEqual(requestLanguage(req({'x-vercel-ip-country':'JP','accept-language':'en-US'})),{language:'ja',source:'country'}));
test('outside Japan defaults to English even with a Japanese browser',()=>{for(const country of ['US','GB','DE','FR','AU','KR'])assert.equal(requestLanguage(req({'x-vercel-ip-country':country,'accept-language':'ja'})).language,'en');});
test('unknown countries use weighted supported browser language; invalid tags are ignored',()=>{for(const country of ['', 'XX','ZZ','JP,US','<script>'])assert.equal(requestLanguage(req({'x-vercel-ip-country':country,'accept-language':'en;q=0.2,ja;q=0.9'})).language,'ja');assert.equal(browserLanguage('ja;q=0,en;q=1'),'en');assert.equal(browserLanguage('fr-FR,de;q=0.5'),'en');assert.equal(browserLanguage('ja;q=invalid,en'),'en');});
test('explicit language overrides country; invalid language does not',()=>{assert.equal(requestLanguage(req({'x-vercel-ip-country':'US','x-practice-language':'ja'})).language,'ja');assert.equal(requestLanguage(req({'x-practice-language':'ja'},'&lang=en')).language,'en');assert.equal(requestLanguage(req({'x-vercel-ip-country':'JP'},'&lang=bad')).language,'ja');assert.equal(requestLanguage(req({'x-test-country':'JP'})).language,'en');});
test('browser preference, fixed language URLs and saved choice have explicit precedence',()=>{assert.equal(initialChoice({url:origin+'/',saved:'ja'}),'ja');assert.equal(initialChoice({url:origin+'/en/app.html',saved:'ja'}),'en');assert.equal(initialChoice({url:origin+'/en/app.html?lang=ja',saved:'en'}),'ja');assert.equal(initialChoice({url:origin+'/?lang=invalid',saved:'invalid'}),null);assert.equal(preferredBrowserLanguage(['fr-FR','ja-JP']),'ja');assert.equal(preferredBrowserLanguage([]),'en');});
test('localized URLs preserve attribution and fragments but never redirect off origin',()=>{const u=languagePath(origin+'/en/app.html?lang=ja&utm_source=instagram#features','ja');assert.equal(u.origin,origin);assert.equal(u.pathname,'/ja/app.html');assert.equal(u.search,'?utm_source=instagram');assert.equal(u.hash,'#features');assert.equal(languagePath(origin+'/','en').pathname,'/en/index.html');});
test('locale endpoint is public, private/no-store and does not call app, DB or providers',async()=>{let calls=0;const h=withLocalization(()=>{calls++;throw Error('must not be called');});const response=await h(req({'x-vercel-ip-country':'JP'}));assert.equal(response.status,200);assert.equal(calls,0);assert.match(response.headers.get('cache-control'),/no-store/);assert.match(response.headers.get('vary'),/X-Vercel-IP-Country/);assert.equal(response.headers.get('content-language'),'ja');assert.deepEqual(await response.json(),{language:'ja',source:'country',languages:['ja','en']});});
test('API errors stay authenticated, retain codes/status and are readable in English',async()=>{const t=setup(),c=client(withLocalization(t.app));const r=await c.call('portfolio',undefined,{}, {'x-practice-language':'en'});assert.equal(r.status,401);assert.equal(r.error.code,'AUTH');assert.match(r.error.message,/sign in/i);const bad=await c.call('register',{username:'a',password:'fixture-password'});assert.equal(bad.status,400);assert.equal(bad.error.code,'USERNAME');assert.match(bad.error.message,/15/);});
test('display localization never translates usernames/comments or alters signed quote data',async()=>{const t=setup(),c=client(withLocalization(t.app));const {account}=await register(c,'売却');const body='総資産 <script>alert(1)</script>';await c.call('comment',{room:'GENERAL',body});const comments=await c.call('comments',undefined,{room:'GENERAL'});assert.equal(comments.items[0].body,body);assert.equal(comments.items[0].username,'売却');const raw=await t.app(new Request(origin+'/api/index?action=quote&symbol=USDJPY',{headers:{cookie:c.cookie}}));const localized=await c.call('quote',undefined,{symbol:'USDJPY'},{'x-practice-language':'en'});const original=await raw.json();assert.deepEqual(localized.quote,original.quote);assert.equal(localized.quoteToken,original.quoteToken);assert.equal((await c.call('session')).account.id,account.id);});
test('buy in English, sell in Japanese and retry: same wallet, history and idempotency',async()=>{const t=setup(),c=client(withLocalization(t.app));await register(c,'Bilingual');const buy=await order(c);assert.equal((await c.call('trade',buy,{}, {'x-practice-language':'en'})).status,200);assert.equal((await c.call('trade',buy,{}, {'x-practice-language':'ja'})).duplicate,true);const sell=await order(c,{side:'sell'});assert.equal((await c.call('trade',sell,{}, {'x-practice-language':'ja'})).status,200);const h=await c.call('history');assert.equal(h.items.length,2);const p=await c.call('portfolio');assert.equal(p.account.state.cashMinor,10000000);assert.equal(p.account.state.positions.length,0);assert.equal(p.account.state.version,2);});
test('missions and achievements localize only display labels, preserving progress IDs',async()=>{const t=setup(),c=client(withLocalization(t.app));await register(c,'MissionsEN');const en=await c.call('progress',undefined,{}, {'x-practice-language':'en'}),ja=await c.call('progress',undefined,{}, {'x-practice-language':'ja'});assert.equal(en.missions[0].label,'Create a practice account');assert.equal(ja.missions[0].label,'仮想口座を作る');assert.deepEqual(en.missions.map(x=>[x.id,x.done]),ja.missions.map(x=>[x.id,x.done]));assert.equal(en.achievements.length,6);assert.deepEqual(en.selected,ja.selected);assert.equal((await c.call('profile-badges',{badges:['profit1000']})).status,403);});
test('source compiler translates static copy, not runtime values, and fails on missing copy',()=>{assert.equal(translateSource('const title="ランキング"; const user=input.username;', {js:true}),'const title="Rankings"; const user=input.username;');assert.throws(()=>translateSource('新規の未翻訳文章'),/Missing English copy/);});
test('built English pages, loader and both bundles are syntactically valid and self-contained',async()=>{
 const {out,bundles}=await buildSite();
 for(const language of ['ja','en']){
  for(const page of ['index.html','app.html','terms.html','privacy.html','data.html']){const s=await readFile(out+'/'+language+'/'+page,'utf8');assert.ok(s.includes(`lang="${language}"`));assert.match(s,/hreflang="en"/);assert.match(s,/locale\.[a-f0-9]{12}\.css/);if(language==='en')assert.doesNotMatch(s,/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u);}
  const manifest=JSON.parse(await readFile(out+'/'+language+'/manifest.json','utf8'));assert.equal(manifest.lang,language);assert.equal(manifest.start_url,'/'+language+'/app.html');assert.equal(manifest.id,'/app.html');
 }
 for(const file of (await readdir(out)).filter(x=>x.endsWith('.js'))){const check=spawnSync(process.execPath,['--check',out+'/'+file],{encoding:'utf8'});assert.equal(check.status,0,check.stderr);}
 const en=await readFile(out+'/'+bundles.en,'utf8');assert.match(en,/X-Practice-Language/);assert.match(en,/currencyDisplay:'code'/);assert.match(en,/Asia\/Tokyo/);assert.doesNotMatch(en,/navigator\.geolocation/);assert.match(en,/esc\(x\.username\)/);assert.match(en,/esc\(x\.body\)/);
});
