import test from 'node:test';import assert from 'node:assert/strict';import {weekWindow,baseline,referenceAt,selectedBadges,unlockedAt,createProgression} from '../lib/progression.mjs';
const at=s=>Date.parse(s),now=at('2026-09-30T12:00:00+09:00'),week=weekWindow(now),initial=10000000;
const position=(symbol,quantity)=>({symbol,quantity,type:'crypto',unit:'BTC',name:'Bitcoin',costMinor:1000000});
function fakeStore(accounts){for(const a of Object.values(accounts))a.state.realizedMinor??=0;return{data:{accounts,progress:{},weekPrices:{}},tail:Promise.resolve(),async transaction(fn){return structuredClone(await fn());}};}
function row(state,extra={}){return{account:{id:'a',username:'Alice',state},walletCreatedAt:at('2026-09-25T12:00:00+09:00'),weekBuyMinor:0,weekSellMinor:0,weekDeltas:[],...extra};}
test('JST Monday boundary and year rollover',()=>{assert.equal(new Date(week.start).toISOString(),'2026-09-27T15:00:00.000Z');assert.equal(weekWindow(week.start-1).end,week.start);assert.equal(weekWindow(week.start).start,week.start);assert.equal(weekWindow(at('2027-01-01T00:00:00+09:00')).label,'2026-12-28');});
test('baseline reverses ledger buys and sells rather than using first visit',()=>{const b=baseline(row({cashMinor:8500000,positions:[position('BTC',1500)],version:3},{weekBuyMinor:2000000,weekSellMinor:500000,weekDeltas:[{symbol:'BTC',quantity:500}]}),week);assert.equal(b.cashMinor,10000000);assert.equal(b.positions[0].quantity,1000);assert.equal(b.at,week.start);});
test('fully sold position still exists in week-start inventory',()=>{const b=baseline(row({cashMinor:11000000,positions:[],version:1},{weekSellMinor:2000000,weekDeltas:[{symbol:'BTC',quantity:-2000}]}),week);assert.deepEqual(b.positions,[{symbol:'BTC',quantity:2000}]);assert.equal(b.cashMinor,9000000);});
test('new participants start from initial virtual cash',()=>{const b=baseline(row({cashMinor:9000000,positions:[position('BTC',1000)],version:1},{walletCreatedAt:week.start+60000,weekBuyMinor:1000000,weekDeltas:[{symbol:'BTC',quantity:1000}]}),week);assert.equal(b.kind,'joined');assert.equal(b.cashMinor,initial);assert.deepEqual(b.positions,[]);});
test('invalid ledger reconstruction stays unknown',()=>{assert.throws(()=>baseline(row({cashMinor:1,positions:[],version:1},{weekDeltas:[{symbol:'BTC',quantity:1000}]}),week));});
test('historical reference never uses a future point or wrong currency',()=>{const c={symbol:'BTC',currency:'JPY',source:'coingecko',points:[{at:week.start-3600000,priceMinor:100},{at:week.start-1000,priceMinor:110},{at:week.start+1,priceMinor:999}]};assert.equal(referenceAt(c,'BTC',week.start).priceMinor,110);assert.throws(()=>referenceAt({...c,points:[{at:week.start+1,priceMinor:999}]},'BTC',week.start));assert.throws(()=>referenceAt({...c,currency:'USD'},'BTC',week.start));assert.throws(()=>referenceAt({...c,points:[{at:week.start-7200001,priceMinor:100}]},'BTC',week.start));});
test('FX uses prior business day without invented weekend rates',()=>{assert.equal(referenceAt({symbol:'USDJPY',currency:'JPY',source:'frankfurter',points:[{at:week.start-2.5*86400000,priceMinor:15000}]},'USDJPY',week.start).priceMinor,15000);});
test('six inclusive thresholds persist and unknown prices cannot unlock',()=>{const stats={cryptoCount:3,fxCount:3};let u=unlockedAt(stats,initial+200000,now);assert.deepEqual(Object.keys(u).sort(),['crypto3','fx3','profit1000','profit2000']);u=unlockedAt(stats,initial-200000,now+1,u);assert.equal(Object.keys(u).length,6);assert.deepEqual(unlockedAt({cryptoCount:0,fxCount:0},null,now,{}),{});assert.deepEqual(unlockedAt(stats,initial,now+2,u),u);assert.equal(unlockedAt(stats,initial+99999,now).profit1000,undefined);});
test('only zero to three distinct earned badges can be selected',()=>{const u={profit1000:1,profit2000:1,crypto3:1,fx3:1};assert.deepEqual(selectedBadges(['profit2000','crypto3','fx3'],u),['profit2000','crypto3','fx3']);assert.deepEqual(selectedBadges([],u),[]);for(const ids of [['profit1000','profit2000','crypto3','fx3'],['fx3','fx3'],['loss1000'],['<script>'],[null],null])assert.throws(()=>selectedBadges(ids,u));});
test('missions and trade counts use entire ledger; selection survives reload',async()=>{const a={id:'a',username:'Alice',createdAt:week.start+1,state:{cashMinor:initial,positions:[],version:6},trades:Array.from({length:60},(_,i)=>({symbol:i<3?'BTC':'USDJPY',side:i%2?'buy':'sell',executedAt:week.start+2,totalMinor:100,quantity:1000000}))};const store=fakeStore({a}),p=createProgression({store,market:{},clock:()=>now});let r=await p.profile('a');assert.equal(r.stats.cryptoCount,3);assert.equal(r.stats.fxCount,57);assert.equal(r.missions.find(m=>m.id==='chart').done,false);await p.observe(a,initial,'chart');await p.observe(a,initial,'portfolio');r=await p.profile('a');assert.ok(r.missions.every(m=>m.done));await p.setBadges('a',['crypto3','fx3']);assert.deepEqual((await createProgression({store,market:{},clock:()=>now}).profile('a')).selected,['crypto3','fx3']);});
test('stale valuation cannot unlock against a newer wallet',async()=>{const a={id:'a',username:'Alice',createdAt:now,state:{cashMinor:initial,positions:[],version:2},trades:[]},store=fakeStore({a}),p=createProgression({store,market:{},clock:()=>now});await p.observe({...a,state:{...a.state,version:1}},initial+200000,'portfolio');assert.equal(store.data.progress.a.unlocked.profit1000,undefined);assert.equal(store.data.progress.a.portfolioSeen,false);});
test('weekly and total metrics differ; negative gains are ranked and reference is frozen',async()=>{const a={id:'a',username:'Alice',createdAt:week.start-86400000,state:{cashMinor:9000000,positions:[position('BTC',1000)],version:0},trades:[]},b={id:'b',username:'Bob',createdAt:week.start+1,state:{cashMinor:10100000,positions:[],version:0},trades:[]},store=fakeStore({a,b}),before=structuredClone(store.data.accounts);let calls=0;const market={quote:async symbol=>({symbol,priceMinor:2000000000}),history:async symbol=>{calls++;return{symbol,currency:'JPY',source:'coingecko',points:[{at:week.start-1000,priceMinor:3000000000}]};}},p=createProgression({store,market,clock:()=>now});assert.equal((await p.rankings('a','total')).items[0].username,'Alice');const w=await p.rankings('a','weekly');assert.equal(w.items[0].username,'Bob');assert.equal(w.items.find(r=>r.username==='Alice').weeklyChangeMinor,-1000000);await p.rankings('a','weekly');assert.equal(calls,1);assert.deepEqual(store.data.accounts,before);assert.equal(w.items[0].account,undefined);assert.equal(w.items[0].positions,undefined);});
test('missing historical price does not fabricate weekly score or break total mode',async()=>{const a={id:'a',username:'Alice',createdAt:week.start-1,state:{cashMinor:9000000,positions:[position('BTC',1000)],version:0},trades:[]},p=createProgression({store:fakeStore({a}),market:{quote:async()=>({priceMinor:1000000000}),history:async()=>{throw Error('budget exhausted');}},clock:()=>now});const w=await p.rankings('a','weekly');assert.equal(w.items[0].weeklyChangeMinor,null);assert.equal(w.items[0].rank,null);assert.equal((await p.rankings('a','total')).items[0].totalMinor,initial);});
