import { AppError, invariant, amountMinor, INITIAL_CASH, validateState } from './domain.mjs';
import { assetFor } from './catalog.mjs';
const DAY=86400000,WEEK=7*DAY,JST=9*3600000;
export const ACHIEVEMENTS=Object.freeze([
 {id:'profit1000',label:'＋1,000円突破',short:'+1,000',icon:'🌱',description:'総資産が初期10万円より1,000円以上増えた'},
 {id:'profit2000',label:'＋2,000円突破',short:'+2,000',icon:'🌟',description:'総資産が初期10万円より2,000円以上増えた'},
 {id:'crypto3',label:'仮想通貨3売買',short:'Crypto ×3',icon:'🪙',description:'仮想通貨の購入・売却を合計3回成立させた'},
 {id:'fx3',label:'FX3売買',short:'FX ×3',icon:'💱',description:'FXの購入・売却を合計3回成立させた'},
 {id:'loss1000',label:'−1,000円を経験',short:'−1,000',icon:'📘',description:'総資産が初期10万円より1,000円以上減った経験'},
 {id:'loss2000',label:'−2,000円を経験',short:'−2,000',icon:'📙',description:'総資産が初期10万円より2,000円以上減った経験'}
]);
const IDS=new Set(ACHIEVEMENTS.map(a=>a.id));
export function weekWindow(now){invariant(Number.isSafeInteger(now)&&now>0,'WEEK','集計日時を確認できません。',500);const d=new Date(now+JST),day=(d.getUTCDay()+6)%7,start=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-JST-day*DAY;return{start,end:start+WEEK,label:new Date(start+JST).toISOString().slice(0,10),timezone:'Asia/Tokyo'};}
export function selectedBadges(value,unlocked){invariant(Array.isArray(value)&&value.length<=3&&value.every(x=>typeof x==='string'&&IDS.has(x))&&new Set(value).size===value.length,'BADGES','獲得済みの実績を重複なしで3つまで選んでください。');invariant(value.every(x=>Object.hasOwn(unlocked||{},x)),'BADGE_LOCKED','未獲得の実績は設定できません。',403);return[...value];}
export function unlockedAt(stats,total,now,previous={}){const next={...previous},pnl=Number.isSafeInteger(total)?total-INITIAL_CASH:null;for(const[id,yes]of[['profit1000',pnl!==null&&pnl>=100000],['profit2000',pnl!==null&&pnl>=200000],['crypto3',stats.cryptoCount>=3],['fx3',stats.fxCount>=3],['loss1000',pnl!==null&&pnl<=-100000],['loss2000',pnl!==null&&pnl<=-200000]])if(yes&&!Object.hasOwn(next,id))next[id]=now;return next;}
// Reverse the immutable ledger to recover week-start INVENTORY, even without midnight traffic.
export function baseline(row,week){if(row.walletCreatedAt>=week.start)return{cashMinor:INITIAL_CASH,positions:[],at:row.walletCreatedAt,kind:'joined'};const cash=row.account.state.cashMinor+row.weekBuyMinor-row.weekSellMinor;invariant(Number.isSafeInteger(cash)&&cash>=0&&cash<=1e12,'WEEK_BASELINE','週初の残高を確認できません。',503);const quantities=new Map(row.account.state.positions.map(p=>[p.symbol,p.quantity]));for(const delta of row.weekDeltas||[])quantities.set(delta.symbol,(quantities.get(delta.symbol)||0)-delta.quantity);const positions=[];for(const[symbol,quantity]of quantities){const a=assetFor(symbol);invariant(a&&Number.isSafeInteger(quantity)&&quantity>=0&&quantity<=1e12&&quantity%a.stepUnits===0,'WEEK_BASELINE','週初の保有数量を確認できません。',503);if(quantity)positions.push({symbol,quantity});}return{cashMinor:cash,positions,at:week.start,kind:'week-start'};}
export function referenceAt(chart,symbol,start){const a=assetFor(symbol);invariant(a&&chart?.symbol===symbol&&chart.currency==='JPY'&&chart.source===a.source&&Array.isArray(chart.points),'WEEK_PRICE','週初の参考価格を確認できません。',503);const candidates=chart.points.filter(p=>Number.isSafeInteger(p.at)&&p.at<=start&&Number.isSafeInteger(p.priceMinor)&&p.priceMinor>0&&p.priceMinor<=1e12),point=candidates.reduce((best,p)=>!best||p.at>best.at?p:best,null),maxAge=a.type==='crypto'?7200000:10*DAY;invariant(point&&start-point.at<=maxAge,'WEEK_PRICE','週初以前の参考価格がありません。',503);return{weekStart:start,symbol,priceMinor:point.priceMinor,priceAt:point.at,source:a.source,granularity:a.type==='crypto'?'hourly':'business-daily'};}
function validRef(ref,symbol,start){const a=assetFor(symbol);return a&&ref?.weekStart===start&&ref.symbol===symbol&&ref.source===a.source&&Number.isSafeInteger(ref.priceMinor)&&ref.priceMinor>0&&ref.priceMinor<=1e12&&Number.isSafeInteger(ref.priceAt)&&ref.priceAt<=start&&start-ref.priceAt<=(a.type==='crypto'?7200000:10*DAY);}
function memoryRow(store,a,week){const trades=a.trades||[],recent=trades.filter(t=>t.executedAt>=week.start),deltas=new Map();for(const t of recent)deltas.set(t.symbol,(deltas.get(t.symbol)||0)+(t.side==='buy'?1:-1)*t.quantity);return{account:{id:a.id,username:a.username,market:'multi',state:structuredClone(a.state),createdAt:a.createdAt},walletCreatedAt:a.walletCreatedAt??a.createdAt,buyCount:trades.filter(t=>t.side==='buy').length,sellCount:trades.filter(t=>t.side==='sell').length,cryptoCount:trades.filter(t=>assetFor(t.symbol)?.type==='crypto').length,fxCount:trades.filter(t=>assetFor(t.symbol)?.type==='fx').length,weekBuyMinor:recent.filter(t=>t.side==='buy').reduce((s,t)=>s+t.totalMinor,0),weekSellMinor:recent.filter(t=>t.side==='sell').reduce((s,t)=>s+t.totalMinor,0),weekDeltas:[...deltas].map(([symbol,quantity])=>({symbol,quantity})),progress:structuredClone(store.data.progress?.[a.id]||{})};}
export function createProgression({store,market,clock=Date.now}){
 const inFlight=new Map();
 async function snapshots(accountId=null,week=weekWindow(clock())){if(typeof store.request!=='function'){await store.tail;return Object.values(store.data.accounts).filter(a=>!accountId||a.id===accountId).map(a=>memoryRow(store,a,week));}const all=[];let after=null;for(let page=0;page<100;page++){const batch=await store.request('rpc/practice_progress_snapshots','POST',{p_account_id:accountId,p_after:after,p_week_start:week.start});invariant(Array.isArray(batch),'PROGRESS','進捗を取得できません。',503);all.push(...batch);if(batch.length<500)return all;after=batch.at(-1).account.id;}throw new AppError('RANKING_BUSY','ランキングの処理上限に達しました。',503);}
 async function observe(account,total=null,event=''){if(!['','chart','portfolio'].includes(event))throw new AppError('PROGRESS_EVENT','操作を確認できません。');if(typeof store.request==='function')return store.request('rpc/practice_progress_observe','POST',{p_account_id:account.id,p_version:account.state.version,p_total_minor:total,p_event:event});return store.transaction(()=>{const a=store.data.accounts[account.id];invariant(a,'AUTH','ログインしてください。',401);store.data.progress??={};const p=store.data.progress[a.id]??={unlocked:{},selected:[],chartSeen:false,portfolioSeen:false},row=memoryRow(store,a,weekWindow(clock())),current=a.state.version===account.state.version;p.unlocked=unlockedAt(row,current?total:null,clock(),p.unlocked);if(event==='chart')p.chartSeen=true;if(event==='portfolio'&&current&&total!==null)p.portfolioSeen=true;return p;});}
 async function valueRows(rows){const quotes={},symbols=[...new Set(rows.flatMap(r=>{validateState(r.account.state);return r.account.state.positions.map(p=>p.symbol);}))];await Promise.all(symbols.map(async symbol=>{try{quotes[symbol]=await market.quote(symbol);}catch{}}));return rows.map(row=>{const s=row.account.state,complete=s.positions.every(p=>quotes[p.symbol]),total=complete?s.cashMinor+s.positions.reduce((n,p)=>n+amountMinor(quotes[p.symbol].priceMinor,p.quantity),0):null;return{...row,totalMinor:total};});}
 async function profile(accountId){const rows=await valueRows(await snapshots(accountId));invariant(rows.length===1,'AUTH','ログインしてください。',401);const row=rows[0],p=await observe(row.account,row.totalMinor),missions=[{id:'account',label:'仮想口座を作る',description:'仮想の10万円でスタート',done:true},{id:'chart',label:'チャートを見る',description:'相場の動きとデータの日付を確認',done:!!p.chartSeen},{id:'buy',label:'はじめての仮想購入',description:'好きな銘柄を少額で体験',done:row.buyCount>0},{id:'sell',label:'はじめての仮想売却',description:'保有した銘柄を売ってみる',done:row.sellCount>0},{id:'portfolio',label:'資産と損益を確認',description:'仮想資産の増減を振り返る',done:!!p.portfolioSeen}];return{missions,achievements:ACHIEVEMENTS.map(a=>({...a,earnedAt:p.unlocked?.[a.id]??null})),selected:p.selected||[],stats:{buyCount:row.buyCount,sellCount:row.sellCount,cryptoCount:row.cryptoCount,fxCount:row.fxCount},totalMinor:row.totalMinor};}
 async function setBadges(accountId,ids){const[row]=await snapshots(accountId);invariant(row,'AUTH','ログインしてください。',401);const selected=selectedBadges(ids,row.progress.unlocked||{});if(typeof store.request==='function'){const r=await store.request('rpc/practice_select_badges','POST',{p_account_id:accountId,p_selected:selected});invariant(r?.ok,'BADGE_LOCKED','獲得済みの実績を3つまで選んでください。',403);return{selected:r.selected};}return store.transaction(()=>{const a=store.data.accounts[accountId];invariant(a,'AUTH','ログインしてください。',401);store.data.progress??={};const p=store.data.progress[accountId]??={unlocked:{}};p.selected=selectedBadges(selected,p.unlocked);return{selected:p.selected};});}
 async function weeklyReference(symbol,week){const key=`${week.start}:${symbol}`;async function get(){if(typeof store.request==='function'){const[r]=await store.request(`practice_week_prices?week_start=eq.${week.start}&symbol=eq.${encodeURIComponent(symbol)}&select=week_start,symbol,price_minor,price_at,source,granularity&limit=1`);return r?{weekStart:r.week_start,symbol:r.symbol,priceMinor:r.price_minor,priceAt:r.price_at,source:r.source,granularity:r.granularity}:null;}await store.tail;return store.data.weekPrices?.[key]||null;}const cached=await get();if(cached){invariant(validRef(cached,symbol,week.start),'WEEK_PRICE','基準価格を確認できません。',503);return cached;}if(inFlight.has(key))return inFlight.get(key);const task=(async()=>{const a=assetFor(symbol),chart=await market.history(symbol,a.type==='crypto'?'30D':'1M'),ref=referenceAt(chart,symbol,week.start);if(typeof store.request==='function')await store.request('practice_week_prices?on_conflict=week_start,symbol','POST',{week_start:ref.weekStart,symbol,price_minor:ref.priceMinor,price_at:ref.priceAt,source:ref.source,granularity:ref.granularity},'resolution=ignore-duplicates,return=minimal');else await store.transaction(()=>{store.data.weekPrices??={};store.data.weekPrices[key]??=ref;});const canonical=await get();invariant(validRef(canonical,symbol,week.start),'WEEK_PRICE','基準価格を保存できません。',503);return canonical;})().finally(()=>inFlight.delete(key));inFlight.set(key,task);return task;}
 async function rankings(accountId,mode='total'){invariant(['total','weekly'].includes(mode),'RANKING_MODE','ランキングの種類が正しくありません。');const now=clock(),week=weekWindow(now),rows=await valueRows(await snapshots(null,week)),refs={},failed=new Set();if(mode==='weekly'){for(const row of rows)try{row.base=baseline(row,week);}catch{row.base=null;}const symbols=[...new Set(rows.flatMap(r=>r.base?.positions.map(p=>p.symbol)||[]))];await Promise.all(symbols.map(async symbol=>{try{refs[symbol]=await weeklyReference(symbol,week);}catch{failed.add(symbol);}}));}
 for(let i=0;i<rows.length;i+=10)await Promise.all(rows.slice(i,i+10).map(async r=>{const previous=r.progress?.unlocked||{},next=unlockedAt(r,r.totalMinor,now,previous);if(Object.keys(next).length>Object.keys(previous).length)try{r.progress=await observe(r.account,r.totalMinor);}catch{r.progress=r.progress||{};}}));
 const items=rows.map(r=>{let baseMinor=null,weeklyChangeMinor=null;if(mode==='weekly'&&r.base&&r.base.positions.every(p=>refs[p.symbol])){baseMinor=r.base.cashMinor+r.base.positions.reduce((n,p)=>n+amountMinor(refs[p.symbol].priceMinor,p.quantity),0);if(r.totalMinor!==null)weeklyChangeMinor=r.totalMinor-baseMinor;}return{username:r.account.username,totalMinor:r.totalMinor,sellCount:r.sellCount,me:r.account.id===accountId,badges:(r.progress.selected||[]).filter(id=>r.progress.unlocked?.[id]).slice(0,3),weeklyChangeMinor,baselineAt:mode==='weekly'?r.base?.at??null:null,baselineKind:mode==='weekly'?r.base?.kind??null:null};});const metric=r=>mode==='weekly'?r.weeklyChangeMinor:r.totalMinor;items.sort((a,b)=>(metric(a)===null)-(metric(b)===null)||(metric(b)??0)-(metric(a)??0)||a.username.localeCompare(b.username,'ja'));let rank=0,previous=null;const ranked=items.map((r,i)=>{const value=metric(r);if(value!==null&&value!==previous)rank=i+1;previous=value;return{...r,rank:value===null?null:rank};});return{items:ranked,mode,week:mode==='weekly'?week:null,referencePrices:mode==='weekly'?Object.values(refs):[],unavailableSymbols:[...failed],valuedAt:now};}
 return{profile,setBadges,observe,rankings,snapshots};
}
