import { randomUUID } from 'node:crypto';
import { normalizeSupabaseUrl } from './config.mjs';
import { initialState, AppError, invariant } from './domain.mjs';
const safe=a=>a?{id:a.id,username:a.username,market:'multi',state:structuredClone(a.state),createdAt:a.createdAt}:null;
export class MemoryStore {
  constructor(data=null){this.data=data||{accounts:{},sessions:{},buckets:{},cache:{},chartCache:{},chartBudget:{window:'',count:0}};this.data.cache??={};this.data.chartCache??={};this.data.chartBudget??={window:'',count:0};this.data.comments??=[];this.tail=Promise.resolve();}
  async transaction(fn){const task=this.tail.then(async()=>{const before=structuredClone(this.data);try{const r=await fn();await this.persist();return structuredClone(r);}catch(e){this.data=before;throw e;}});this.tail=task.catch(()=>{});return task;}
  async persist(){}
  async register(c,market,username){return this.transaction(()=>{const accounts=Object.values(this.data.accounts);invariant(!accounts.some(a=>a.lookup===c.lookup),'PASSWORD_UNAVAILABLE','このパスワードは使えません。別のものを作成してください。',409);invariant(!accounts.some(a=>a.username.toLowerCase()===username.toLowerCase()),'USERNAME_UNAVAILABLE','このユーザーネームは使われています。',409);const a={id:randomUUID(),...c,username,market:'multi',state:initialState(),createdAt:Date.now(),trades:[]};this.data.accounts[a.id]=a;return safe(a);});}
  async findCredential(lookup){await this.tail;const a=Object.values(this.data.accounts).find(a=>a.lookup===lookup);return a?{id:a.id,salt:a.salt,hash:a.hash}:null;}
  async getAccount(id){await this.tail;return safe(this.data.accounts[id]);}
  async updateUsername(id,username){return this.transaction(()=>{const a=this.data.accounts[id];invariant(a,'AUTH','ログインしてください。',401);invariant(!Object.values(this.data.accounts).some(b=>b.id!==id&&b.username.toLowerCase()===username.toLowerCase()),'USERNAME_UNAVAILABLE','このユーザーネームは使われています。',409);a.username=username;return safe(a);});}
  async leaderboardAccounts(){await this.tail;return Object.values(this.data.accounts).map(a=>({...safe(a),sellCount:(a.trades||[]).filter(t=>t.side==='sell').length}));}
  async newSession(hash,id,expiresAt){return this.transaction(()=>{invariant(this.data.accounts[id],'AUTH','ログインしてください。',401);this.data.sessions[hash]={accountId:id,expiresAt};});}
  async sessionAccount(hash,now){await this.tail;const s=this.data.sessions[hash];return s&&s.expiresAt>now?this.getAccount(s.accountId):null;}
  async logout(hash){return this.transaction(()=>{delete this.data.sessions[hash];});}
  async deleteAccount(id){return this.transaction(()=>{for(const [k,s]of Object.entries(this.data.sessions))if(s.accountId===id)delete this.data.sessions[k];this.data.comments=this.data.comments.filter(x=>x.accountId!==id);delete this.data.accounts[id];});}
  async comments(room,limit=50){await this.tail;return this.data.comments.filter(x=>x.room===room).sort((a,b)=>b.createdAt-a.createdAt).slice(0,limit).map(x=>({id:x.id,room:x.room,body:x.body,createdAt:x.createdAt,username:this.data.accounts[x.accountId]?.username||'削除済み'}));}
  async addComment(accountId,room,body,createdAt){return this.transaction(()=>{const a=this.data.accounts[accountId];invariant(a,'AUTH','ログインしてください。',401);const row={id:randomUUID(),accountId,room,body,createdAt};this.data.comments.push(row);return{id:row.id,room,body,createdAt,username:a.username};});}
  async deleteComment(accountId,id){return this.transaction(()=>{const i=this.data.comments.findIndex(x=>String(x.id)===String(id)&&x.accountId===accountId);invariant(i>=0,'COMMENT_NOT_FOUND','コメントが見つかりません。',404);this.data.comments.splice(i,1);return true;});}
  async getTrade(id,requestId){await this.tail;return structuredClone(this.data.accounts[id]?.trades.find(t=>t.requestId===requestId)||null);}
  async history(id,offset=0,limit=50){await this.tail;const a=this.data.accounts[id],rows=[...(a?.trades||[]),...(a?.legacyTrades||[])].sort((a,b)=>b.executedAt-a.executedAt);return {items:structuredClone(rows.slice(offset,offset+limit)),hasMore:rows.length>offset+limit};}
  async commit(id,version,state,trade,fingerprint){return this.transaction(()=>{const a=this.data.accounts[id];invariant(a,'AUTH','ログインしてください。',401);const old=a.trades.find(t=>t.requestId===trade.requestId);if(old){invariant(old.fingerprint===fingerprint,'IDEMPOTENCY_CONFLICT','同じ注文番号で異なる注文は送れません。',409);return{duplicate:true,state:a.state,trade:old};}if(a.state.version!==version)return{conflict:true};a.state=state;const saved={...trade,fingerprint};a.trades.push(saved);return{duplicate:false,state,trade:saved};});}
  async rate(key,limit,windowMs,now){return this.transaction(()=>{const bucket=Math.floor(now/windowMs),b=this.data.buckets[key];if(!b||b.bucket!==bucket)this.data.buckets[key]={bucket,count:1};else b.count++;return this.data.buckets[key].count<=limit;});}
  async getCache(key){await this.tail;return structuredClone(this.data.cache[key]||null);}
  async claimCache(key,now){return this.transaction(()=>{const c=this.data.cache[key];if(c&&now<c.nextFetchAt)return{claimed:false,cached:c};const token=randomUUID();this.data.cache[key]={payload:null,fetchedAt:now,nextFetchAt:now+300000,token};return{claimed:true,token};});}
  async saveCache(key,token,record){return this.transaction(()=>{if(this.data.cache[key]?.token===token)this.data.cache[key]={...record,token};});}
  async failCache(key,token,error,retryMs){return this.transaction(()=>{const c=this.data.cache[key];if(c?.token===token){c.error=error;c.nextFetchAt=c.fetchedAt+retryMs;}});}
  async getChartCache(key){await this.tail;return structuredClone(this.data.chartCache[key]||null);}
  async claimChartCache(key,now,ttlMs){return this.transaction(()=>{const c=this.data.chartCache[key];if(c&&now<c.nextFetchAt)return{claimed:false,cached:c};if(/^chart:(BTC|ETH|SOL|XRP):/.test(key)){const window=new Date(now).toISOString().slice(0,7);if(this.data.chartBudget.window!==window)this.data.chartBudget={window,count:0};if(this.data.chartBudget.count>=500){const d=new Date(now),next=Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1);const cached={payload:null,fetchedAt:now,nextFetchAt:next,error:'CHART_BUDGET'};this.data.chartCache[key]=cached;return{claimed:false,cached};}this.data.chartBudget.count++;}const token=randomUUID();this.data.chartCache[key]={payload:null,fetchedAt:now,nextFetchAt:now+ttlMs,token,error:null};return{claimed:true,token};});}
  async saveChartCache(key,token,record){return this.transaction(()=>{if(this.data.chartCache[key]?.token===token)this.data.chartCache[key]={...record,token};});}
  async failChartCache(key,token,error,retryMs){return this.transaction(()=>{const c=this.data.chartCache[key];if(c?.token===token){c.error=error;c.payload=null;c.nextFetchAt=c.fetchedAt+retryMs;}});}
}
const accountSelect='id,username,market,created_at,practice_wallets(state)';
export class SupabaseStore {
  constructor(url,key,fetcher=fetch){url=normalizeSupabaseUrl(url);invariant(url,'CONFIG','データベース設定を確認してください。',503);this.url=`${url}/rest/v1`;this.key=key;this.fetcher=fetcher;}
  async request(path,method='GET',body,prefer='return=representation') {
    let r;try{r=await this.fetcher(`${this.url}/${path}`,{method,headers:{apikey:this.key,...(this.key.startsWith('sb_secret_')?{}:{Authorization:`Bearer ${this.key}`}), 'Content-Type':'application/json',Prefer:prefer},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(8000)});}catch{throw new AppError('DB_UNAVAILABLE','口座に接続できません。同じ注文の再送では二重取引しません。',503);}
    let data;try{const text=await r.text();data=text?JSON.parse(text):null;}catch{throw new AppError('DB_UNAVAILABLE','口座の応答を読み取れません。',503);}
    if(!r.ok){if(data?.code==='23505')throw new AppError(/username/i.test(data.message||'')?'USERNAME_UNAVAILABLE':'PASSWORD_UNAVAILABLE',/username/i.test(data.message||'')?'このユーザーネームは使われています。':'このパスワードは使えません。別のものを作成してください。',409);throw new AppError('DB_UNAVAILABLE','口座データを確認できません。管理者の設定を確認してください。',503);}return data;
  }
  account(r){if(!r)return null;const wallet=Array.isArray(r.practice_wallets)?r.practice_wallets[0]:r.practice_wallets;invariant(wallet?.state,'MIGRATION_REQUIRED','新しい練習口座の移行準備中です。記録は保持されています。',503);return{id:r.id,username:r.username,market:'multi',state:wallet.state,createdAt:Date.parse(r.created_at)};}
  async register(c,market,username){const [r]=await this.request('practice_accounts','POST',{lookup:c.lookup,salt:c.salt,password_hash:c.hash,username,market:'multi',state:initialState()});return this.getAccount(r.id);}
  async findCredential(lookup){const[r]=await this.request(`practice_accounts?lookup=eq.${encodeURIComponent(lookup)}&select=id,salt,password_hash&limit=1`);return r?{id:r.id,salt:r.salt,hash:r.password_hash}:null;}
  async getAccount(id){const[r]=await this.request(`practice_accounts?id=eq.${encodeURIComponent(id)}&select=${accountSelect}&limit=1`);return this.account(r);}
  async updateUsername(id,username){await this.request(`practice_accounts?id=eq.${encodeURIComponent(id)}`,'PATCH',{username},'return=minimal');return this.getAccount(id);}
  async leaderboardAccounts(){const counts=await this.request('rpc/practice_leaderboard_sell_counts','POST',{}),sell=new Map(counts.map(r=>[r.account_id,Number(r.sell_count)||0])),rows=[];let last='';for(let page=0;page<100;page++){const batch=await this.request(`practice_accounts?select=${accountSelect}&order=id.asc&limit=500${last?`&id=gt.${last}`:''}`);rows.push(...batch.map(r=>({...this.account(r),sellCount:sell.get(r.id)||0})));if(batch.length<500)return rows;last=batch.at(-1).id;}throw new AppError('RANKING_BUSY','ランキングの処理上限に達しました。',503);}
  async newSession(hash,id,expiresAt){await this.request('practice_sessions','POST',{token_hash:hash,account_id:id,expires_at:new Date(expiresAt).toISOString()});await this.request(`practice_sessions?expires_at=lt.${encodeURIComponent(new Date().toISOString())}`,'DELETE',undefined,'return=minimal').catch(()=>{});}
  async sessionAccount(hash,now){const[r]=await this.request(`practice_sessions?token_hash=eq.${hash}&expires_at=gt.${encodeURIComponent(new Date(now).toISOString())}&select=account_id&limit=1`);return r?this.getAccount(r.account_id):null;}
  async logout(hash){await this.request(`practice_sessions?token_hash=eq.${hash}`,'DELETE',undefined,'return=minimal');}
  async deleteAccount(id){await this.request(`practice_accounts?id=eq.${encodeURIComponent(id)}`,'DELETE',undefined,'return=minimal');}
  async comments(room,limit=50){const rows=await this.request(`practice_comments?room=eq.${encodeURIComponent(room)}&select=id,room,body,created_at,account_id,practice_accounts(username)&order=created_at.desc,id.desc&limit=${limit}`);return rows.map(r=>({id:r.id,room:r.room,body:r.body,createdAt:Date.parse(r.created_at),username:(Array.isArray(r.practice_accounts)?r.practice_accounts[0]:r.practice_accounts)?.username||'削除済み'}));}
  async addComment(accountId,room,body){const [r]=await this.request('practice_comments','POST',{account_id:accountId,room,body});return{id:r.id,room:r.room,body:r.body,createdAt:Date.parse(r.created_at),username:(await this.getAccount(accountId)).username};}
  async deleteComment(accountId,id){const rows=await this.request(`practice_comments?id=eq.${encodeURIComponent(id)}&account_id=eq.${encodeURIComponent(accountId)}&select=id`);invariant(rows.length,'COMMENT_NOT_FOUND','コメントが見つかりません。',404);await this.request(`practice_comments?id=eq.${encodeURIComponent(id)}&account_id=eq.${encodeURIComponent(accountId)}`,'DELETE',undefined,'return=minimal');return true;}
  async getTrade(id,requestId){const[r]=await this.request(`practice_asset_trades?account_id=eq.${encodeURIComponent(id)}&request_id=eq.${encodeURIComponent(requestId)}&select=trade,fingerprint&limit=1`);return r?{...r.trade,fingerprint:r.fingerprint}:null;}
  async history(id,offset=0,limit=50){return this.request('rpc/practice_asset_history','POST',{p_account_id:id,p_offset:offset,p_limit:limit});}
  async commit(id,version,state,trade,fingerprint){const r=await this.request('rpc/practice_commit_asset_trade','POST',{p_account_id:id,p_expected_version:version,p_state:state,p_trade:trade,p_fingerprint:fingerprint});invariant(!r.idempotencyConflict,'IDEMPOTENCY_CONFLICT','同じ注文番号で異なる注文は送れません。',409);return r;}
  async rate(key,limit,windowMs,now){return this.request('rpc/practice_rate_limit','POST',{p_key:key,p_limit:limit,p_window_ms:windowMs,p_now_ms:now});}
  async getCache(key){const[r]=await this.request(`practice_quote_cache?key=eq.${key}&select=payload,fetched_at,next_fetch_at,error_code&limit=1`);return r?{payload:r.payload,fetchedAt:r.fetched_at,nextFetchAt:r.next_fetch_at,error:r.error_code}:null;}
  async claimCache(key){return this.request('rpc/practice_claim_quotes','POST',{p_key:key});}
  async saveCache(key,token,r){await this.request('rpc/practice_save_quotes','POST',{p_key:key,p_token:token,p_payload:r.payload,p_fetched_at:r.fetchedAt});}
  async failCache(key,token,error,retryMs){await this.request('rpc/practice_fail_quotes','POST',{p_key:key,p_token:token,p_error:error,p_retry_ms:retryMs});}
  async getChartCache(key){const[r]=await this.request(`practice_chart_cache?key=eq.${encodeURIComponent(key)}&select=payload,fetched_at,next_fetch_at,error_code&limit=1`);return r?{payload:r.payload,fetchedAt:r.fetched_at,nextFetchAt:r.next_fetch_at,error:r.error_code}:null;}
  async claimChartCache(key,now,ttlMs){return this.request('rpc/practice_claim_chart','POST',{p_key:key,p_ttl_ms:ttlMs});}
  async saveChartCache(key,token,r){await this.request('rpc/practice_save_chart','POST',{p_key:key,p_token:token,p_payload:r.payload,p_fetched_at:r.fetchedAt,p_next_fetch_at:r.nextFetchAt});}
  async failChartCache(key,token,error,retryMs){await this.request('rpc/practice_fail_chart','POST',{p_key:key,p_token:token,p_error:error,p_retry_ms:retryMs});}
}
